/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/mideaPage': RouteRecordInfo<'/mideaPage', '/mideaPage', Record<never, never>, Record<never, never>>,
    '/pagePage': RouteRecordInfo<'/pagePage', '/pagePage', Record<never, never>, Record<never, never>>,
    '/userPage': RouteRecordInfo<'/userPage', '/userPage', Record<never, never>, Record<never, never>>,
  }
}
